# Generated by Django 5.0.2 on 2024-02-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseNumber', models.CharField(max_length=255)),
                ('caseParticipant', models.CharField(max_length=255)),
                ('caseCategory', models.CharField(max_length=255)),
            ],
        ),
    ]
